#!/usr/bin/env python3
"""
ACMS Memory Generator - Create realistic memories at scale

Generates 100,000 diverse memories simulating a 5,000-person Bay Area tech company.
Includes variety of topics, lengths, and realistic Q&A patterns.

Usage:
    python scripts/generate_memories.py --count 100000 --batch-size 500 --delay 2
"""

import asyncio
import random
import time
import argparse
import logging
import uuid
from datetime import datetime, timedelta
from typing import List, Dict, Tuple
import sys
import os

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.storage.memory_crud import MemoryCRUD
from src.storage.database import get_session
from sqlalchemy import text

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('memory_generation.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


# ============================================================================
# MEMORY TEMPLATES - Realistic Q&A patterns for Bay Area tech company
# ============================================================================

MEMORY_TEMPLATES = {
    # Software Engineering & Debugging (20%)
    "software_engineering": [
        ("How do I debug a React component that's not re-rendering?",
         "Check if you're mutating state directly instead of creating a new object. Use React DevTools to inspect component props and state. Verify useEffect dependencies are correct. Consider using React.memo() for performance optimization."),

        ("What's causing this 'Cannot read property of undefined' error?",
         "This typically means you're trying to access a property on an object that doesn't exist yet. Add optional chaining (obj?.property) or check if the object exists before accessing. Common in async data fetching - add loading states."),

        ("How to fix PostgreSQL connection pool exhausted error?",
         "Increase max_connections in postgresql.conf, implement connection pooling with pgBouncer, ensure connections are properly closed after use, check for connection leaks in your code, monitor active connections with pg_stat_activity."),

        ("Best practices for API error handling in FastAPI?",
         "Use HTTPException for standard errors, create custom exception handlers with @app.exception_handler, return consistent error response format, log errors with request context, use Pydantic for request validation, implement rate limiting."),
    ],

    # AI/ML & LLMs (15%)
    "ai_ml": [
        ("How to reduce hallucinations in LLM responses?",
         "Use retrieval-augmented generation (RAG), provide clear context and constraints in prompts, implement fact-checking mechanisms, use lower temperature settings, break complex queries into steps, validate outputs against source material."),

        ("What's the difference between GPT-4 and Claude Sonnet?",
         "GPT-4 has larger context window (128K), Claude Sonnet has better reasoning and code generation, different pricing models, Claude is better for long documents, GPT-4 has multimodal capabilities, both support function calling."),

        ("How to fine-tune a model without overfitting?",
         "Use cross-validation, implement early stopping, add dropout layers, use data augmentation, regularization (L1/L2), monitor validation loss, use learning rate scheduling, keep training set balanced, use transfer learning."),

        ("Explain vector embeddings for semantic search",
         "Embeddings are dense numerical representations of text that capture semantic meaning. Similar concepts are close in vector space. Generated by models like OpenAI text-embedding-ada-002. Used for similarity search, clustering, classification. Stored in vector databases like Weaviate."),
    ],

    # Cloud & DevOps (12%)
    "devops_cloud": [
        ("How to optimize Docker image build time?",
         "Use multi-stage builds, leverage build cache, order Dockerfile commands by change frequency, use .dockerignore, minimize layers, use specific base images, pre-build dependencies, use BuildKit, implement layer caching in CI/CD."),

        ("Kubernetes pod keeps crashing with OOMKilled",
         "Increase memory limits in deployment spec, check memory usage with kubectl top, look for memory leaks, optimize application memory usage, use horizontal pod autoscaling, set appropriate resource requests and limits, check Java heap settings."),

        ("How to set up CI/CD pipeline for microservices?",
         "Use GitHub Actions or GitLab CI, implement containerization, use Kubernetes for orchestration, set up automated testing, implement blue-green deployments, use ArgoCD for GitOps, monitor with Prometheus, implement canary releases."),

        ("AWS S3 costs getting too high, how to reduce?",
         "Use S3 Intelligent-Tiering, implement lifecycle policies, compress objects, use CloudFront CDN, delete unused objects, use S3 Glacier for archives, enable S3 Storage Lens, optimize data transfer, use S3 Select for queries."),
    ],

    # Web Development (10%)
    "web_development": [
        ("Next.js vs Create React App - which to use?",
         "Use Next.js for SEO-critical apps (blogs, e-commerce), server-side rendering, API routes, better performance. Use CRA for internal tools, SPAs, prototypes. Next.js has better DX, built-in optimization, but steeper learning curve."),

        ("How to implement infinite scroll in React?",
         "Use Intersection Observer API, libraries like react-infinite-scroll-component, implement lazy loading, fetch data on scroll, debounce scroll events, add loading indicators, handle edge cases, optimize for mobile."),

        ("CSS Grid vs Flexbox - when to use each?",
         "Use Grid for 2D layouts (rows and columns), complex page layouts, card grids. Use Flexbox for 1D layouts (single row/column), navigation bars, centering items. Grid is more powerful, Flexbox is simpler for linear layouts."),

        ("Performance optimization tips for React apps",
         "Use React.memo, useCallback, useMemo for expensive computations, code splitting with lazy loading, virtualize long lists, optimize images, minimize bundle size, use CDN, implement caching, avoid inline functions in JSX."),
    ],

    # Data Science & Analytics (8%)
    "data_science": [
        ("How to handle imbalanced datasets in classification?",
         "Use SMOTE for oversampling minority class, undersampling majority class, adjust class weights, use ensemble methods, try different evaluation metrics (F1, precision, recall), collect more data, use anomaly detection approaches."),

        ("pandas merge vs join vs concat - when to use?",
         "Use merge for SQL-like joins on columns, join for index-based joining, concat for stacking DataFrames vertically or horizontally. Merge is most flexible, join is faster for index operations, concat for simple stacking."),

        ("Best practices for data visualization",
         "Choose right chart type, use clear labels and titles, limit colors (use colorblind-friendly palettes), show data context, avoid 3D charts, use interactive plots when needed, keep it simple, highlight key insights."),

        ("How to optimize slow pandas operations?",
         "Use vectorized operations instead of apply, use category dtype for strings, avoid iterrows, use query() for filtering, implement chunking for large files, consider Dask or Polars, use numba for numerical operations."),
    ],

    # Security & Compliance (7%)
    "security": [
        ("How to implement OAuth2 authentication?",
         "Use authorization code flow, implement PKCE for SPAs, secure token storage, use HTTPS only, implement token refresh, add rate limiting, validate redirect URIs, use state parameter for CSRF protection, implement proper scopes."),

        ("GDPR compliance checklist for SaaS app",
         "Implement data portability, add cookie consent, create privacy policy, enable data deletion, encrypt data at rest and in transit, implement audit logging, appoint DPO if needed, handle data breaches properly, get user consent."),

        ("Prevent SQL injection in Python apps",
         "Use parameterized queries, ORM frameworks (SQLAlchemy), input validation, least privilege database accounts, escape user input, use prepared statements, implement WAF, regular security audits, sanitize inputs."),

        ("How to secure API endpoints?",
         "Implement authentication (JWT, OAuth), use HTTPS, rate limiting, input validation, CORS configuration, API keys for service-to-service, implement logging and monitoring, use API gateway, regular security testing."),
    ],

    # Finance & Stocks (6%)
    "finance": [
        ("Best practices for expense reporting?",
         "Use Expensify or Concur, submit within 30 days, include itemized receipts, categorize correctly, get manager approval, follow per diem limits, separate personal and business expenses, keep digital copies."),

        ("How does 401k matching work at our company?",
         "Company matches 50% up to 6% of salary, vested immediately, contribution limits $22,500 (2023), can change contribution anytime, invest in target-date funds or custom allocation, consider Roth option, max out for full match."),

        ("Understanding stock options vs RSUs",
         "Stock options give right to buy at strike price, RSUs are actual shares that vest. Options have potential upside if stock price increases, RSUs have guaranteed value. RSUs taxed at vest, options at exercise. Consider AMT for ISOs."),

        ("Current market trends in tech stocks",
         "AI companies seeing growth, interest rates affecting valuations, focus on profitability over growth, cloud spending stabilizing, cybersecurity demand increasing, semiconductor shortage improving, remote work tools consolidating."),
    ],

    # Bay Area Life & Commute (8%)
    "bay_area": [
        ("Best time to commute from San Jose to SF?",
         "Avoid 7-9am and 4-7pm peak hours. Take Caltrain at 6:30am or after 9:30am. BART is faster but more crowded. Consider bike to station. Highway 101 takes 1-2 hours during rush. I-280 is scenic alternative. Carpool lane saves time."),

        ("Where to park near Caltrain in Mountain View?",
         "Park free at Castro St station before 9am (limited spots), use Evelyn Ave garage ($3/day), bike from nearby streets, use scooter from downtown, consider monthly permit ($80), arrive early for spots."),

        ("Good lunch spots near Palo Alto office?",
         "Oren's Hummus (University Ave), Tootsie's (Castro St), LYFE Kitchen, Chipotle, Sweetgreen, Zareen's for Pakistani, Sushi Tomi, Vina Enoteca, The Counter, Coupa Café. Order ahead to save time."),

        ("How to avoid 101 traffic to South Bay?",
         "Take Caltrain, use I-280, try Page Mill Road, consider leaving before 3pm or after 7pm, work from home on Fridays, use Waze for real-time routing, carpool for express lanes, bike if close."),
    ],

    # HR & Benefits (5%)
    "hr_benefits": [
        ("How to request PTO through Workday?",
         "Log into Workday > Time Off > Request Time Off > Select dates and PTO type > Add notes > Submit to manager. Get approval before booking travel. Minimum 2 weeks notice for vacation. Check balance first."),

        ("What's covered under our health insurance?",
         "Medical, dental, vision included. $20 copay for primary care, $40 specialist. Free preventive care. Mental health covered (10 sessions). Prescriptions through CVS. FSA available. Dependents covered. Annual deductible $1500."),

        ("Remote work policy guidelines",
         "Work remote 3 days/week max, require manager approval, maintain availability during core hours (10am-4pm PT), join video for standups, document work, home office stipend $500, must be in state, VPN required."),

        ("New employee onboarding checklist",
         "Complete I-9, set up direct deposit, enroll in benefits (30 days), get laptop and badge, attend orientation, set up accounts (Slack, email, GitHub), meet team, review handbook, complete trainings, 30-60-90 day plan."),
    ],

    # Product & Strategy (5%)
    "product": [
        ("How to prioritize features in backlog?",
         "Use RICE scoring (Reach, Impact, Confidence, Effort), consider user feedback, align with OKRs, assess technical debt, evaluate competitive landscape, analyze metrics, consult stakeholders, balance quick wins vs long-term bets."),

        ("Writing effective user stories",
         "Use format: As a [user], I want to [action], so that [benefit]. Add acceptance criteria, include edge cases, size appropriately, add mockups, define done, consider technical constraints, get stakeholder review."),

        ("Measuring product-market fit",
         "Track retention rates, NPS scores, user engagement, organic growth, customer feedback, churn rate, time to value, feature adoption, revenue growth, would users be disappointed if product disappeared (>40% = good fit)."),

        ("Running effective sprint retrospectives",
         "Use start/stop/continue format, gather feedback anonymously, focus on actions not blame, time-box to 1 hour, rotate facilitator, track action items, measure improvements, try different formats, ensure psychological safety."),
    ],

    # Office & IT (4%)
    "office_it": [
        ("WiFi keeps dropping in conference room 3B",
         "Submit IT ticket, try different network (Guest vs Employee), check access point status, restart device, update WiFi drivers, use Ethernet adapter, sit closer to AP, check for interference, IT usually responds in 2 hours."),

        ("How to request new equipment or software?",
         "Submit request through ServiceNow, get manager approval, specify business justification, IT reviews in 3-5 days, track status in portal, expedite if urgent, consider budget cycle, approved tools list in wiki."),

        ("VPN connection issues troubleshooting",
         "Restart VPN client, check internet connection, verify credentials, try different VPN server, update VPN software, check firewall settings, clear DNS cache, disable other VPNs, contact IT if persists, use backup VPN."),

        ("Conference room booking best practices",
         "Book through Outlook calendar, include video link, add agenda, invite attendees, check equipment beforehand, cancel if not needed, limit to necessary attendees, end on time, have backup room, report issues to facilities."),
    ],
}

# Additional topic categories for variety
ADDITIONAL_TOPICS = {
    "quantum_computing": [
        ("Explain quantum entanglement simply", "Quantum entanglement is when two particles become connected such that the state of one instantly affects the other, regardless of distance. Measuring one particle determines the state of the other. Not classical communication - can't send information faster than light. Used in quantum computing and cryptography."),
        ("What are qubits vs classical bits?", "Classical bits are 0 or 1. Qubits can be in superposition - both 0 and 1 simultaneously until measured. This allows quantum computers to process multiple possibilities at once. Qubits are fragile and require extreme cold. Entanglement enables quantum algorithms."),
    ],

    "blockchain": [
        ("How does blockchain consensus work?", "Blockchain consensus mechanisms validate transactions without central authority. Proof of Work (Bitcoin) uses mining, Proof of Stake uses validators based on holdings. Ensures all nodes agree on ledger state. Prevents double-spending. Byzantine fault tolerance."),
        ("Smart contracts explained", "Smart contracts are self-executing code on blockchain. Automatically enforce agreement terms. Written in Solidity (Ethereum) or other languages. Immutable once deployed. Enable DeFi, NFTs, DAOs. Gas fees for execution. Audit critical for security."),
    ],

    "mobile_dev": [
        ("Swift vs SwiftUI for iOS development", "SwiftUI is declarative, modern, cross-platform (iOS, macOS, watchOS). Swift is the language. Use SwiftUI for new projects (iOS 13+). UIKit still needed for complex UI, legacy code. SwiftUI has faster development, less boilerplate."),
        ("React Native performance optimization", "Use FlatList for long lists, optimize images, minimize bridge usage, use native modules for heavy tasks, implement memoization, profile with Flipper, reduce re-renders, lazy load components, use Hermes engine."),
    ],

    "sales_marketing": [
        ("Improving email open rates", "Personalize subject lines, send at optimal times (10am Tue-Thu), segment audience, A/B test, keep concise, mobile optimize, avoid spam triggers, use clear CTAs, clean email list, track metrics."),
        ("Calculating customer acquisition cost", "CAC = Total Sales & Marketing Spend / New Customers Acquired. Include salaries, tools, ads, events. Track by channel. Compare to LTV (should be 3:1 ratio). Aim to reduce over time. Monitor payback period."),
    ],
}

# Merge additional topics
MEMORY_TEMPLATES.update(ADDITIONAL_TOPICS)


async def fetch_user_ids() -> List[str]:
    """Fetch all user_ids from the database."""
    try:
        async with get_session() as db:
            query = text("SELECT user_id FROM users WHERE is_active = true")
            result = await db.execute(query)
            user_ids = [str(row[0]) for row in result.fetchall()]
            logger.info(f"Fetched {len(user_ids)} active user IDs from database")
            return user_ids
    except Exception as e:
        logger.error(f"Error fetching user IDs: {e}")
        return []


def generate_memory_batch(batch_size: int, user_ids: List[str]) -> List[Dict]:
    """Generate a batch of realistic memories with variety in topics and length."""
    memories = []

    # Weight categories by frequency
    categories = list(MEMORY_TEMPLATES.keys())
    weights = [
        20,  # software_engineering
        15,  # ai_ml
        12,  # devops_cloud
        10,  # web_development
        8,   # data_science
        7,   # security
        6,   # finance
        8,   # bay_area
        5,   # hr_benefits
        5,   # product
        4,   # office_it
        # Additional topics get remaining weight
    ] + [3] * (len(categories) - 11)  # Distribute remaining evenly

    for _ in range(batch_size):
        # Select category based on weights
        category = random.choices(categories, weights=weights[:len(categories)])[0]
        templates = MEMORY_TEMPLATES[category]

        # Select random template
        question, answer = random.choice(templates)

        # Vary the length (short/medium/long)
        length_type = random.choices(
            ["short", "medium", "long"],
            weights=[0.3, 0.5, 0.2]
        )[0]

        if length_type == "short":
            # Use answer as-is or trim
            answer_text = answer.split('.')[0] + '.'
        elif length_type == "long":
            # Add more detail
            answer_text = answer + " " + random.choice([
                "This is commonly used in production environments.",
                "Many companies have adopted this approach successfully.",
                "Consider your specific use case when implementing.",
                "Best to test thoroughly before deploying to production.",
                "Check official documentation for latest updates.",
            ])
        else:
            answer_text = answer

        # Create memory
        content = f"Q: {question}\n\nA: {answer_text}"

        # Assign privacy level based on category and realistic distribution
        # PUBLIC: 10% - general knowledge, non-sensitive
        # INTERNAL: 80% - company-specific, most common
        # CONFIDENTIAL: 10% - sensitive, proprietary

        # Some categories are more likely to be CONFIDENTIAL
        if category in ["security", "finance", "hr_benefits"]:
            privacy_level = random.choices(
                ["PUBLIC", "INTERNAL", "CONFIDENTIAL"],
                weights=[0.05, 0.70, 0.25]  # More confidential
            )[0]
        # Some categories are more likely to be PUBLIC
        elif category in ["quantum_computing", "blockchain", "ai_ml", "software_engineering"]:
            privacy_level = random.choices(
                ["PUBLIC", "INTERNAL", "CONFIDENTIAL"],
                weights=[0.20, 0.75, 0.05]  # More public
            )[0]
        else:
            # Default distribution
            privacy_level = random.choices(
                ["PUBLIC", "INTERNAL", "CONFIDENTIAL"],
                weights=[0.10, 0.80, 0.10]
            )[0]

        # Randomly select a user from the pool
        selected_user_id = random.choice(user_ids) if user_ids else "default"

        memory = {
            "content": content,
            "user_id": selected_user_id,
            "tags": [category.replace('_', '-'), "generated", "qa", privacy_level.lower()],
            "privacy_level": privacy_level,
            "source": "generated",  # source, not source_type
            "metadata": {
                "generated": True,
                "category": category,
                "length_type": length_type,
                "question": question,
                "answer": answer_text
            }
        }

        memories.append(memory)

    return memories


async def insert_memories_batch(memory_crud: MemoryCRUD, memories: List[Dict]):
    """Insert a batch of memories into the database."""
    try:
        for memory in memories:
            await memory_crud.create_memory(**memory)
        return True
    except Exception as e:
        logger.error(f"Error inserting batch: {e}")
        return False


async def generate_memories_async(
    total_count: int,
    batch_size: int,
    delay: float,
    user_id: str = None
):
    """Generate memories asynchronously with batching and rate limiting."""
    # Fetch all user IDs from the database
    logger.info("Fetching user IDs from database...")
    user_ids = await fetch_user_ids()

    if not user_ids:
        logger.error("No user IDs found in database. Please run create_users.py first.")
        return 0, 0

    logger.info(f"Will distribute memories across {len(user_ids)} users")

    memory_crud = MemoryCRUD()

    total_batches = (total_count + batch_size - 1) // batch_size
    successful = 0
    failed = 0

    logger.info(f"Starting memory generation: {total_count} total, {batch_size} per batch")
    logger.info(f"Estimated time: {(total_batches * delay) / 60:.1f} minutes")

    start_time = time.time()

    for batch_num in range(total_batches):
        batch_start = time.time()

        # Generate batch
        current_batch_size = min(batch_size, total_count - (batch_num * batch_size))
        memories = generate_memory_batch(current_batch_size, user_ids)

        # Insert batch
        success = await insert_memories_batch(memory_crud, memories)

        if success:
            successful += current_batch_size
        else:
            failed += current_batch_size

        # Progress reporting
        progress = ((batch_num + 1) / total_batches) * 100
        elapsed = time.time() - start_time
        rate = successful / elapsed if elapsed > 0 else 0
        eta = (total_count - successful) / rate if rate > 0 else 0

        logger.info(
            f"Batch {batch_num + 1}/{total_batches} ({progress:.1f}%) | "
            f"Success: {successful} | Failed: {failed} | "
            f"Rate: {rate:.1f}/s | ETA: {eta/60:.1f}m"
        )

        # Rate limiting - wait between batches
        if batch_num < total_batches - 1:  # Don't wait after last batch
            await asyncio.sleep(delay)

    # Final summary
    elapsed_total = time.time() - start_time
    logger.info(f"\n{'='*60}")
    logger.info(f"Memory Generation Complete!")
    logger.info(f"{'='*60}")
    logger.info(f"Total generated: {successful}")
    logger.info(f"Failed: {failed}")
    logger.info(f"Time taken: {elapsed_total/60:.1f} minutes")
    logger.info(f"Average rate: {successful/elapsed_total:.1f} memories/second")
    logger.info(f"{'='*60}")

    return successful, failed


def main():
    parser = argparse.ArgumentParser(
        description="Generate realistic memories for ACMS at scale"
    )
    parser.add_argument(
        "--count",
        type=int,
        default=100000,
        help="Number of memories to generate (default: 100000)"
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=500,
        help="Memories per batch (default: 500)"
    )
    parser.add_argument(
        "--delay",
        type=float,
        default=2.0,
        help="Delay between batches in seconds (default: 2.0)"
    )
    parser.add_argument(
        "--user-id",
        type=str,
        default="default",
        help="User ID for memories (default: 'default')"
    )

    args = parser.parse_args()

    logger.info(f"Configuration:")
    logger.info(f"  Total memories: {args.count:,}")
    logger.info(f"  Batch size: {args.batch_size}")
    logger.info(f"  Delay: {args.delay}s")
    logger.info(f"  User ID: {args.user_id}")

    # Run async generation
    asyncio.run(generate_memories_async(
        args.count,
        args.batch_size,
        args.delay,
        args.user_id
    ))


if __name__ == "__main__":
    main()
